// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uphnfxygkagrxyodonzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwaG5meHlna2Fncnh5b2RvbnpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTQ2MDUsImV4cCI6MjA2NjY5MDYwNX0.zxKrfCcwFBqoawyFyjcLufYjQEs0DHo5DjDkJaJY3LI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);